apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: acrpublicforctooffice.azurecr.io/ks-guestbook-demo:0.x
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: HEAD
  name: imageupdater-guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/toomone/argocd-example-apps
    targetRevision: HEAD